name: 'sample ci'

on:
  - push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: hoge
        run: echo "Hello, World!"
      - name: show branch name
        run: echo "${{GITHUB_REF}}"
