name: 'sample ci'

on:
  - push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: hoge
        run: echo "Hello, World!"
      - name: show branch name
        run: echo ${GITHUB_REF##*/}
  specified_job:
    name: specified
    runs-on: ubuntu-latest
    if: ${GITHUB_REF#refs/heads/} == 'release/staging' || ${GITHUB_REF#refs/heads/} == 'release/production'
    steps:
      - name: echo something if branch name is release
        run: echo ${GITHUB_REF#refs/heads/}
